# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2019-01-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="mvpuser", name="user"),
        migrations.RemoveField(model_name="userrole", name="role"),
        migrations.RemoveField(model_name="userrole", name="user"),
        migrations.DeleteModel(name="MVPUser"),
        migrations.DeleteModel(name="Role"),
        migrations.DeleteModel(name="UserRole"),
    ]
